#!/usr/bin/env python

# This script should work in python 2 *or* 3. It loads emar.py, which needs python 2.

from tools.toolchain_profiler import ToolchainProfiler

import sys
from tools import shared

if sys.version_info.major == 2:
  if __name__ == '__main__':
    ToolchainProfiler.record_process_start()
    import emar
    emar.run()
    sys.exit(0)
else:
  import os, subprocess
  if __name__ == '__main__':
    sys.exit(subprocess.call([shared.PYTHON, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'emar.py')] + sys.argv[1:]))
